spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active: native #使用本地配置 需要注释掉git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hibss/spring-cloud-config-server.git
          username: zhongba520@126.com
          password: sheng@1009
          search-paths: config-server
          basedir: config-repo
server:
  port: 9005
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true  #用不用注册自己
    fetch-registry: true # 要不要去注册中心获取其他服务地址
    service-url:
      defaultZone: http://localhost:8005/eureka/

management:
  security:
    enabled: false   #SpringBoot 1.5.X 以上默认开通了安全认证，如果不关闭会要求权限

